### ISSUE TITLE
Where does zoomOutPercentage option come from?

### ISSUE THREAD

**Issue by json2d** [Neckster/chartjs-plugin-piechart-outlabels#9]
So in this example code: https://piechart-outlabels.netlify.com/quickstart

there's an option called `zoomOutPercentage`.

But I can't find any references to this option in chartjs docs. Where is it from? Is it from another plugin?

I have some issues with getting the entire piechart to fit in the canvas, and it seems this option is suppose to help.

**Comment by json2d** [comment]
Ok so `zoomOutPercentage` belongs to this plugin. I was confused by the scoping of it in the `options` object.

ref: https://github.com/Neckster/chartjs-plugin-piechart-outlabels/blob/dbd276fd81b1ef1e2e90b266bf0db294ebb463c2/src/outlabeledCharts.js#L23

**Comment by SUVOLewis** [comment]
@json2d Could you please elaborate on this? I'm currently experiencing the same issue as you. I can get the pie charts to render with the labels, but I can't seem to get the zoom to work to allow everything to fit.

![image](https://user-images.githubusercontent.com/42211658/59837860-dfe71280-9345-11e9-8cad-1784cef28f2d.png)

As you can see, I've tried to add "zoomOutPercentage" into various areas within the chart options. Unfortunately, I see no difference.

Also, what chart type were you using? Just a normal 'pie' chart or the provided 'outlabeledPie'?

**Comment by SUVOLewis** [comment]
Just a heads up, for anyone that sees this in the future:

You **MUST** use the 'outlabeledPie' or other plugin-provided outlabeled chart types in order to use the 'zoomOutPercentage' key value.

If you're using ng2-charts, you may run across the 'unsupported chart type' error. To fix this, simply amend your ng2-charts.js file in your node_modules like so:

![image](https://user-images.githubusercontent.com/42211658/59910413-bbed0500-9409-11e9-89f2-01d6b4783852.png)
